### ISSUE TITLE
emulated_dataset characteristics problem

### ISSUE THREAD

**Issue by WzjCoder** [microsoft/RL4BandwidthEstimationChallenge#10]
Is the feature "true_capacity" explained in more detail? Where in the network does it occur? Also, I want to know the chronological order in which true_capacity and true_loss occur. Are they network information after the bandwidth prediction application?

**Comment by skhairy0** [comment]
Hi @WzjCoder, the true capacity and true loss are the characteristics of the bottleneck link. True capacity refers to the capacity of the bottleneck link between the sender and receiver in a given MI. On the other hand, true loss refers to the burst loss rate (percentage of packets which will be thrown away on the way from the sender to receiver) in a given MI. These characteristics are independent of the application of the predicted bandwidth and form the **unobservable** context by the agent (**that's why they cannot be fed in as features to the policy network**). If the arrays in the dataset have nans, you can replace them with the value of the nearest neighbor. Does this answer your question?

**Comment by WzjCoder** [comment]
> Hi @WzjCoder, the true capacity and true loss are the characteristics of the bottleneck link. True capacity refers to the capacity of the bottleneck link between the sender and receiver in a given MI. On the other hand, true loss refers to the burst loss rate (percentage of packets which will be thrown away on the way from the sender to receiver) in a given MI. These characteristics are independent of the application of the predicted bandwidth and form the **unobservable** context by the agent (**that's why they cannot be fed in as features to the policy network**). If the arrays for true capacity/loss in the dataset have some nans, you can replace the nan values with the value of the nearest neighbor. Does this answer your question?

Thank you for your answer
