### ISSUE TITLE
What is the interval between the On and On+1 in the dataset

### ISSUE THREAD

**Issue by OIIAIIOOIIAII** [microsoft/RL4BandwidthEstimationChallenge#4]

**Comment by Wanghaha2333** [comment]
It seems 60ms, but I don't know if the interval between given bandwidth is also 60ms?

**Comment by OIIAIIOOIIAII** [comment]
@Wanghaha2333 doesn't seems like 60ms though. If the interval is 60ms, then the closest MI data of first sample should be equivalent to the second closest MI data of the second sample, which is not the case in current dataset. So, I assume that the interval is an unknown number which is not 60ms.

**Comment by n13eho** [comment]
it can be deduced from [this script released recently](https://github.com/microsoft/RL4BandwidthEstimationChallenge/blob/main/run_baseline_model.py#L36C14-L36C14) that the interval is 60ms

**Comment by skhairy0** [comment]
At every step, we get the receive time of the most recent packet and chunk the history in 60ms intervals. Received packets are then grouped into these MIs and the network metrics are computed (by averaging) accordingly. Because the reference time in each POMDP step is that of the most recently received packet, the MIs won't align perfectly as you described @OIIAIIOOIIAII (not a shift right operation). Our test client works in the same fashion, so as long as the policy predicts a_n based on o_n (and h_{n-1}/c_{n-1}), there won't be any issues.

cc: @Wanghaha2333, @n13eho
